version: '3.8'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri file:///mlruns
    volumes:
      - ./mlruns:/mlruns
    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:5000/api/2.0/mlflow/experiments/list"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s

  flask_app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    # depends_on:
    #   mlflow:
    #     condition: service_healthy
    command: python main.py