name: "build_backend_image"

on:
  push:
    branches:
      - "**"

jobs:
  backend_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_KEY }}"

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker login for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      - name: Build and Push Backend Image
        run: |
          cd services/backend
          IMAGE=${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend-nubot/backend-service:latest
          docker build -t $IMAGE .
          docker push $IMAGE
          cd ../..
