name: "build_reactfrontned_image"

on:
  push:
    branches:
      - "**"
    paths:
      - "services/frontend1/**"
jobs:
  backend_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_KEY }}"

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker login for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      - name: Build and Push Backend Image
        run: |
          cd services/frontend1
          IMAGE=${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend-nubot/react-service:latest
          docker build -t $IMAGE .
          docker push $IMAGE
          cd ../..

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy react-service \
            --source services/frontend1 \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --memory 1Gi \
            --timeout 3600s \
            --set-env-vars "REACT_APP_API_URL=${{secrets.REACT_APP_API_URL}}"
