name: "build_frontend_image"

on:
  push:
    branches:
      - "**"

jobs:
  frontend_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_KEY }}"

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Docker login for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      - name: Build and Push Frontend Image
        run: |
          cd services/frontend
          IMAGE=${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend-nubot/frontend-service:latest
          docker build -t $IMAGE .
          docker push $IMAGE
          cd ../..

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend-service \
            --source services/frontend \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --memory 1Gi \
            --timeout 1800s \
            --set-env-vars "API_URL=https://backend-service-273412-default.run.app/NuBot"
