name: "gcp_connection"

on:
  push:
    branches:
      - "**"

jobs:
  gcp_connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Repo Success
        run: echo "Cloned repo successfully"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .

      - name: Success Message
        if: success()
        run: echo "Pipeline ran successfully"

      - name: Error Message
        if: failure()
        run: echo "Error during pipeline"

      - name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{secrets.GCP_KEY}}"

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Success Message for cloud
        if: success()
        run: echo "Connection done successfully"

      - name: failure Message for cloud
        if: failure()
        run: echo "Connection to gcloud failed"
