name: Deploy Prefect Flow to Cloud Run

on:
  push:
    branches:
      - "**" # run on commits to any branch (adjust as needed)
  workflow_dispatch: # allow manual trigger from the Actions tab

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_KEY }}"
      # Step 2: Set up gcloud CLI
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Step 3: Configure Docker auth for Artifact Registry
      - name: Docker login for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          cd prefectWorkflows
          docker build \
            -t ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend-nubot/scraperfloe:latest \
            .

      # Step 5: Push the image to Artifact Registry
      - name: Push Docker image
        run: |
          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend-nubot/scraperfloe:latest

      # Step 6: Install Prefect in the runner (for CLI use)
      - name: Install Prefect
        run: pip install --no-cache prefect==2.*

      # Step 7: Register/Update Prefect deployment
      - name: Register Prefect deployment
        run: |
          cd prefectWorkflows
          prefect deployment prefect.yaml --apply
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

      # Step 8: (Optional) Confirm success
      - name: Deployment successful
        run: echo "Prefect flow deployment updated and scheduled successfully."

  deploy-worker:
    needs: build-deploy
    runs-on: ubuntu-latest

    steps:
      - name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_KEY }}"
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy Prefect worker to Cloud Run
        run: |
          gcloud run deploy prefect-worker \
            --image=prefecthq/prefect:3-latest \
            --service-account prefect-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --no-cpu-throttling \
            --platform managed \
            --allow-unauthenticated \
            --memory 4Gi \
            --timeout 3600s \
            --set-env-vars AIRFLOW_UID=5000,BASE_URL=https://www.khoury.northeastern.edu/,MAX_DEPTH=3,CONCURRENT_REQUESTS=10,DATA_FOLDER=scraped_data,MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }},MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }},BUCKET_NAME=${{ secrets.BUCKET_NAME }},RAW_DATA_FOLDER=raw_data,FAISS_INDEX_FOLDER=faiss_index,URLS_LIST=https://www.khoury.northeastern.edu/,PREFECT_API_URL=${{ secrets.PREFECT_API_URL }},PREFECT_API_KEY=${{ secrets.PREFECT_API_KEY }} \
            --args "prefect","worker","start","--pool","my-cloud-run-pool","-t","cloud-run"
