name: Deploy Prefect Flow to Cloud Run

on:
  push:
    branches:
      - "**" # run on commits to main (adjust branch name as needed)
  workflow_dispatch: # allow manual trigger from the Actions tab if needed

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up gcloud CLI
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          credentials_json: "${{ secrets.GCP_KEY }}"

      # Step 3: Configure Docker auth for Artifact Registry
      - name: Docker login for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend-nubot/scraperflow:latest .

      # Step 5: Push the image to Artifact Registry
      - name: Push Docker image
        run: |
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend-nubot/scraperflow:latest

      # Step 6: Install Prefect in the runner (for CLI use)
      - name: Install Prefect
        run: pip install --no-cache prefect==2.*

      # Step 7: Register/Update Prefect deployment
      - name: Register Prefect deployment
        # Use Prefect CLI to build and apply the deployment
        run: |
          prefect deployment build flow.py:scraperflow -n "ScraperFlow Weekly" \
              --pool my-cloud-run-pool -q default \
              --cron "0 9 * * 6" --skip-upload --apply
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

      # Step 8: (Optional) Confirm success
      - name: Deployment successful
        run: echo "Prefect flow deployment updated and scheduled successfully."
