name: Deploy Prefect Flow to Cloud Run

on:
  push:
    branches:
      - main # or any branches you want to trigger the workflow
  workflow_dispatch: # allows manual triggering

env:
  PREFECT_API_URL: https://api.prefect.cloud/api/accounts/${{ secrets.PREFECT_ACCOUNT_ID }}/workspaces/${{ secrets.PREFECT_WORKSPACE_ID }}
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install prefect==2.* python-dotenv

      - name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_KEY }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      - name: Create Prefect Cloud Run pool if not exists
        run: |
          # Check if pool exists, create if it doesn't
          if ! prefect pool ls | grep -q "my-cloud-run-pool"; then
            prefect pool create my-cloud-run-pool --type cloud-run
          fi

          # Check if work queue exists, create if it doesn't
          if ! prefect work-queue ls | grep -q "default"; then
            prefect work-queue create default --pool my-cloud-run-pool
          fi

      - name: Build Docker image
        run: |
          cd prefectWorkflows
          docker build \
            -t ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend-nubot/scraperflow:latest \
            .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend-nubot/scraperflow:latest

      - name: Verify Prefect Connectivity
        run: |
          prefect cloud login -k ${{secrets.PREFECT_API_KEY}}
          prefect config set PREFECT_API_KEY=${{ secrets.PREFECT_API_KEY }}
          prefect config set PREFECT_API_URL=${{ secrets.PREFECT_API_URL }}
          prefect cloud workspace ls

      # If that succeeded, proceed with deployment
      - name: Register Prefect deployment
        run: |
          cd prefectWorkflows
          prefect deploy scraper_flow.py:scraperflow \
            --name "scraperflow-deployment" \
            --description "ScraperFlow Deployment for scraping tasks" \
            --tag scraper --tag production \
            --cron "0 9 * * 6" \
            --pool my-cloud-run-pool \
            --work-queue default

      - name: Deploy Prefect worker to Cloud Run
        run: |
          gcloud run deploy prefect-worker \
            --image=${{ secrets.GCP_ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend-nubot/scraperflow:latest \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --port 8080 \
            --allow-unauthenticated \
            --memory 4Gi \
            --cpu 2 \
            --timeout 3600s \
            --concurrency 80 \
            --set-env-vars AIRFLOW_UID=5000,BASE_URL=https://www.khoury.northeastern.edu/,MAX_DEPTH=3,CONCURRENT_REQUESTS=10,DATA_FOLDER=scraped_data,MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }},MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }},BUCKET_NAME=${{ secrets.BUCKET_NAME }},RAW_DATA_FOLDER=raw_data,FAISS_INDEX_FOLDER=faiss_index,URLS_LIST=https://www.khoury.northeastern.edu/,PREFECT_API_URL= "https://api.prefect.cloud/api/accounts/${{ secrets.PREFECT_ACCOUNT_ID }}/workspaces/${{ secrets.PREFECT_WORKSPACE_ID }}",PREFECT_API_KEY=${{ secrets.PREFECT_API_KEY }}
      - name: Deployment successful
        run: echo "Prefect flow deployment updated and scheduled successfully."
