name: "nu_bot_test"

on:
  push:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - run: echo "copied repository"

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: echo "Setup python"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
      - run: echo "run pip and install dependencies"
        if: success()
      - run: echo "pipeline run sucessfully"
        if: failure()
      - run: echo "error during pipeline"
